### ISSUE TITLE
Screenshots from the project

### ISSUE THREAD

**Issue by vlfom** [ToughDevs/GDK#1]
Guys can someone please upload screenshots of this masterpiece?

**Comment by romanusyk** [comment]
🤣

**Comment by romanusyk** [comment]
i don’t think so 😆

**Comment by vlfom** [comment]
Couldn't resist finally making it run, you can check the demo in the ReadMe now 😄 
Was expecting to see more, but now I recall we were too tired and desperate after writing the shaders haha. Sad we didn't continue with the prey-predator part :)
